#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>
#include "Paint.h"
#include "../Graph.cpp"

class Ui_GuideWindow
{
public:
  Graph g;
  Widget *w;
  QWidget *centralwidget;
  QLabel *TitleLabel;
  QStackedWidget *stackedWidget;
  QWidget *page_1;
  QLabel *info_title;
  QLabel *info_label_1;
  QLabel *info_label_2;
  QLabel *info_label_3;
  QTextEdit *info_text_1;
  QTextEdit *info_text_2;
  QTextEdit *info_text_3;
  QPushButton *info_button_1;
  QTextEdit *info_text_5;
  QLabel *info_label_5;
  QTextEdit *info_text_4;
  QLabel *info_label_4;
  QLabel *info_label_6;
  QTextEdit *info_text_6;
  QPushButton *info_button_2;
  QLabel *info_title_2;
  QPushButton *info_button_3;
  QPushButton *info_button_4;
  QWidget *page_2;
  QLabel *search_title;
  QLabel *search_label_1;
  QTextEdit *search_text_1;
  QPushButton *search_button_1;
  QTextEdit *search_text_2;
  QLabel *search_label_2;
  QLabel *search_title_2;
  QLabel *search_label_3;
  QLabel *search_label_4;
  QTextEdit *search_text_3;
  QTextEdit *search_text_4;
  QPushButton *search_button_2;
  QLabel *search_label_5;
  QTextEdit *search_text_5;
  QWidget *page_3;
  QLabel *road_title;
  QLabel *road_label_1;
  QTextEdit *road_text_1;
  QTextEdit *road_text_2;
  QLabel *road_label_2;
  QTextEdit *road_text_3;
  QPushButton *road_button_1;
  QLabel *road_label_3;
  QWidget *page_4;
  QLabel *multi_title;
  QTextEdit *multi_text_1;
  QLabel *multi_label_2;
  QPushButton *multi_button_1;
  QLabel *multi_label_1;
  QTextEdit *multi_text_2;
  QTextEdit *multi_text_3;
  QLabel *multi_label_3;
  QWidget *page_5;
  QTextEdit *plenty_text_1;
  QTextEdit *plenty_text_4;
  QLabel *plenty_title;
  QLabel *plenty_label_1;
  QLabel *plenty_label_2;
  QPushButton *plenty_button_1;
  QTextEdit *plenty_text_2;
  QLabel *plenty_label_3;
  QTextEdit *plenty_text_3;
  QLabel *plenty_label_4;
  QWidget *page_6;
  QLabel *about_title;
  QLabel *about_label_1;
  QWidget *page_7;
  QLabel *demo_title;
  QPushButton *demo_button_1;
  QLabel *demo_label_2;
  QLabel *demo_label_1;
  QLabel *IconLabel;
  QPushButton *button_left_7;
  QPushButton *button_left_2;
  QPushButton *button_left_1;
  QPushButton *button_left_3;
  QPushButton *button_left_4;
  QPushButton *button_left_6;
  QPushButton *button_left_5;
  QLabel *pix_label_1;
  QLabel *pix_label_2;

public:
  // setupUi
  void setupUi(QMainWindow *GuideWindow);
  // retranslateUi
  void retranslateUi(QMainWindow *GuideWindow);
  // 设定左侧切换事件
  void setLeftEvents();
  // 设定导游系统事件
  void setMainEvents();
  // 设定范例地图
  void setupDemo();
  // 设定最短路径动态演示
  void setPaint();
};
